### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by dzmitry-lahoda** [atifaziz/Interlocker#1]

**Comment by atifaziz** [comment]
[It's there in the README](https://github.com/atifaziz/Interlocker/blob/4ee8be120286bb8f3b5ec805b394e97049bf59f6/README.md).

**Comment by dzmitry-lahoda** [comment]
but not on class itself (no xml comments what ever). such classes are complex to grasp (like interlocked self) - so documentation inline is very important.

**Comment by atifaziz** [comment]
I don't think inline documentation in XML comments beats the usages and examples discussed in the [README](https://github.com/atifaziz/Interlocker/blob/4ee8be120286bb8f3b5ec805b394e97049bf59f6/README.md). There is [so little code in there (10 lines)](https://github.com/atifaziz/Interlocker/blob/4ee8be120286bb8f3b5ec805b394e97049bf59f6/src/Interlocked.cs#L81-L90) that it would be quicker to read than XML comments; those would just bloat up the file.

I don't believe you can understand this project without a good grasp of [`Interlocked.CompareExchange`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.interlocked.compareexchange) first, where and when to use it and how to use it well. This project just helps avoid the boilerplate code you would end up writing again and again, every time you use `Interlocked.CompareExchange`. It does so in a functional way while sacrificing somewhat on micro-optimisations.

**Comment by dzmitry-lahoda** [comment]
Makes sense, if no idea to make the code reusable or usable by others.
