### ISSUE TITLE
Provide non delegate based API to improve perfromance

### ISSUE THREAD

**Issue by dzmitry-lahoda** [atifaziz/Interlocker#3]
If I use interlocked I hope it is fast. As of now (guess) current API will give 30% of slowness I do not need.
```
        public TResult Update<TUpdate, TResult>(
            Func<T, int, TUpdate, TUpdate> updater,
            Func<TUpdate, T> replacementSelector,
Func<TUpdate, TResult> resultSelector)
```

So, may be there should be API to provide just values for comparison(most common cases), to avoid delegate call overhead?

**Comment by atifaziz** [comment]
If you want the tightest and fastest code, use `Interlocked.CompareExchange` directly. That said, `Interlocked.CompareExchange` by itself is not fast. It's just an optimistic locking strategy. Every failed `Interlocked.CompareExchange` will cause you to do work again and possibly waste some cycles using a spin-wait. The rationale is that it's still quicker than switching threads, incurring a context-switch. You have to weigh all that against the cost of a delegate invocation.

**Comment by dzmitry-lahoda** [comment]
i guess using `lock` will make more sense in 99% of cases, given `Interlocker` is not optimized. and using `Interlocked` directly also another 99% of cases.

**Comment by atifaziz** [comment]
Get `lock` right is easy but not always optimal. `Interlocked` can be optimal but hard to get right. I say therefore, know your case, measure and decide.

I also like the approach: [make it work, might it right and then make it fast](http://wiki.c2.com/?MakeItWorkMakeItRightMakeItFast). With `Interlocked` from this proejct, I like to get it right and _fast enough_.
