### ISSUE TITLE
Create internal update which is called by other updates which does not null checks.

### ISSUE THREAD

**Issue by dzmitry-lahoda** [atifaziz/Interlocker#6]
```
        private TResult UpdateInternal<TUpdate, TResult>(
            Func<T, int, TUpdate, TUpdate> updater,
            Func<TUpdate, T> replacementSelector,
            Func<TUpdate, TResult> resultSelector)
{
```

**Comment by atifaziz** [comment]
Why? What are you trying to gain? Null checks are cheap compared to everything else going on in a compare-exchange.

**Comment by dzmitry-lahoda** [comment]
reduce the gap - eventually all small items sum up to large one - compared to direct usage of  interlocked act per se with custom code around. 
but if no idea to make `Interlocker` reusable - never mind than.

**Comment by atifaziz** [comment]
> but if no idea to make `Interlocker` reusable

Um, it's not reusable? `Update` is the reusable abstraction here. Abstractions, however, have a cost and that may be fine as long as you understand and accept them. If it's not acceptable then hand-roll your most optimal case. Alternatively, reduce the cost of abstractions in the compiler and runtime.
